### ISSUE TITLE
getting Error:  Package missing in current win-64 channels

### ISSUE THREAD

**Issue by Coderx7** [conda-forge/leveldb-feedstock#2]
Hello, 
When I'm trying to install this is the error I get :

```
[Anaconda2] C:\Users\4Bros>conda install leveldb
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current win-64 channels:
  - leveldb

You can search for this package on anaconda.org with

    anaconda search -t conda leveldb
```

How can I solve this ?
Thanks in advance

**Comment by jakirkham** [comment]
That's because there are no Windows packages. If you would like to try to build `leveldb` on Windows, I would gladly accept a PR.

**Comment by jakirkham** [comment]
Should add that upstream is still trying to figure out how to do this as Windows is not a supported platform as of yet.

xref: https://github.com/google/leveldb/issues/363

**Comment by jakirkham** [comment]
Just an update, upstream added CMake support in commit ( https://github.com/google/leveldb/commit/739c25100e46576cdcdfff2d6f43f9f7008103c7 ). Now we just need a release that includes that change. Asked upstream about this.
